/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'cosmetics' : null } |
  { 'mens' : null } |
  { 'womens' : null };
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'thana' : string,
  'deliveryCharge' : bigint,
  'mobileNumber' : string,
  'productId' : bigint,
  'productName' : string,
  'district' : string,
  'grandTotal' : bigint,
  'timestamp' : bigint,
  'quantity' : bigint,
  'fullAddress' : string,
  'subtotal' : bigint,
}
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'subcategory' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'offerPrice' : bigint,
  'category' : Category,
  'regularPrice' : bigint,
}
export interface SupportMessage {
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'mobile' : string,
}
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getSupportMessages' : ActorMethod<[], Array<SupportMessage>>,
  'initialize' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, string, bigint, bigint],
    bigint
  >,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'sendSupportMessage' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];