/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'thana' : IDL.Text,
  'deliveryCharge' : IDL.Nat,
  'mobileNumber' : IDL.Text,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'district' : IDL.Text,
  'grandTotal' : IDL.Nat,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'fullAddress' : IDL.Text,
  'subtotal' : IDL.Nat,
});
export const Category = IDL.Variant({
  'cosmetics' : IDL.Null,
  'mens' : IDL.Null,
  'womens' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'offerPrice' : IDL.Nat,
  'category' : Category,
  'regularPrice' : IDL.Nat,
});
export const SupportMessage = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'mobile' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getSupportMessages' : IDL.Func([], [IDL.Vec(SupportMessage)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'sendSupportMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'thana' : IDL.Text,
    'deliveryCharge' : IDL.Nat,
    'mobileNumber' : IDL.Text,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'district' : IDL.Text,
    'grandTotal' : IDL.Nat,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'fullAddress' : IDL.Text,
    'subtotal' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'cosmetics' : IDL.Null,
    'mens' : IDL.Null,
    'womens' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'offerPrice' : IDL.Nat,
    'category' : Category,
    'regularPrice' : IDL.Nat,
  });
  const SupportMessage = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'mobile' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSupportMessages' : IDL.Func([], [IDL.Vec(SupportMessage)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'sendSupportMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };